#!/usr/bin/env node
/**
 * Build per-platform MAIN-world overlay scripts from src/*-main/ directories.
 *
 * Each directory becomes public/{dir}.js (e.g. src/bm-main -> public/bm-main.js).
 * Modules inside a directory are concatenated in sorted order and wrapped in
 * an IIFE with a per-directory injection guard.
 *
 * A variant may compose in shared modules (see SHARED_INCLUDES): the variant's
 * own files (e.g. 00-config.js) are concatenated first, then the shared files.
 * This lets the volcengine Agent/Coding Plan overlays share one implementation
 * (src/volc-shared) while each keeps only its 00-config.js. Shared dirs do not
 * end in "-main", so they are never emitted as standalone outputs.
 */
const fs = require('fs');
const path = require('path');

const ROOT_DIR = path.join(__dirname, '..');
const SRC_ROOT = path.join(ROOT_DIR, 'src');
const PUBLIC_DIR = path.join(ROOT_DIR, 'public');

// Injected into overlay sources as a last-resort version fallback (used only
// when the runtime cannot read the manifest version). Source files write the
// literal token `__PKG_VERSION__`; this keeps them from drifting from
// package.json.
const PKG_VERSION = JSON.parse(fs.readFileSync(path.join(ROOT_DIR, 'package.json'), 'utf8')).version;

// Variant dir -> shared source dirs concatenated after the variant's own files.
const SHARED_INCLUDES = {
  'volc-agentplan-main': ['volc-shared'],
  'volc-codingplan-main': ['volc-shared'],
};

function collectJsFiles(dirName) {
  const dir = path.join(SRC_ROOT, dirName);
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.js'))
    .sort()
    .map(f => ({ label: `${dirName}/${f}`, fullPath: path.join(dir, f) }));
}

function buildPlatformMain(dirName) {
  const outFile = path.join(PUBLIC_DIR, `${dirName}.js`);

  // Own files first (so 00-config.js defines config before shared modules use
  // it), then any shared includes.
  const entries = [
    ...collectJsFiles(dirName),
    ...(SHARED_INCLUDES[dirName] || []).flatMap(collectJsFiles),
  ];

  if (entries.length === 0) {
    console.error(`No module files found for ${dirName}`);
    return false;
  }

  const modules = entries.map(({ label, fullPath }) => {
    const content = fs.readFileSync(fullPath, 'utf8');
    return `// ── ${label} ──\n${content}`;
  });

  const guardVar = `_inj_${dirName.replace(/-/g, '_')}`;
  const rawOutput = `// MAIN world script — ${dirName}
// AUTO-GENERATED by scripts/build-overlay.js — DO NOT EDIT DIRECTLY
(function() {
  if (window['${guardVar}']) return;
  window['${guardVar}'] = true;

${modules.join('\n\n')}

})();
`;

  const output = rawOutput.replace(/__PKG_VERSION__/g, PKG_VERSION);

  fs.writeFileSync(outFile, output, 'utf8');
  console.log(`Built ${outFile} from ${entries.length} modules (${(output.length / 1024).toFixed(1)}KB)`);
  return true;
}

function main() {
  if (!fs.existsSync(PUBLIC_DIR)) {
    fs.mkdirSync(PUBLIC_DIR, { recursive: true });
  }

  const entries = fs.readdirSync(SRC_ROOT, { withFileTypes: true });
  const platformDirs = entries
    .filter(e => e.isDirectory() && e.name.endsWith('-main'))
    .map(e => e.name)
    .sort();

  if (platformDirs.length === 0) {
    console.error('No src/*-main directories found');
    process.exit(1);
  }

  let built = 0;
  for (const dir of platformDirs) {
    if (buildPlatformMain(dir)) built++;
  }

  console.log(`Built ${built} platform MAIN-world script(s)`);
}

main();
